### ISSUE TITLE
Add missing timeouts to http requests

### ISSUE THREAD

**Issue by badrogger** [skalenetwork/sgx.py#167]
Production code should have timeout logic for each http request. Without it process may stuck forever and it will much harder to handle it. Right now timeouts are missing in every request.

**Comment by PolinaKiporenko** [comment]
Related to node rotation

**Comment by DmytroNazarenko** [comment]
skale-admin: 2.6.0-beta.0
skale.py: 6.2b0
sgx.py: 0.9dev2

**Comment by yatsunastya** [comment]
Due to complicated setting and low possibility on Mainnet, define it like unverifiable.
